services:
  planning-poker:
    image: ghcr.io/andrew-busbee/planning-poker:latest
    pull_policy: always        # always pull the newest :latest on start (Otional)
    ports:
      - "3005:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/decks', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
