services:
  planning-poker:
    image: andrewbusbee/planning-poker:latest
    user: "9999:9999"  # nodejs user:group for writing game data to /app/data
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/decks', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
